[package]
name = "leaf-sdk-macro"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0.66"
bytes = "1.3.0"
http = "0.2.8"
leaf-sdk = { path = "../leaf-sdk" }
quote = "1.0.21"
syn = "1.0.105"
wit-bindgen-guest-rust = { git = "https://github.com/bytecodealliance/wit-bindgen" }

[lib]
proc-macro = true
