version: '3'

networks:
  leaf_serverless_network:
    external: true

services:
  redis-server:
    image: redis:7.0
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass f94c09e66e8864085ee1b435055cd8e79dcb7faf5d4bf5a52896ca1a589ea8b7
    volumes:
      - ./redis_data:/data
    networks:
      - leaf_serverless_network
  reverse-proxy:
    image: traefik:v2.9
    command: --api.insecure=true --providers.redis.endpoints=redis-server:6379 --providers.redis.password=f94c09e66e8864085ee1b435055cd8e79dcb7faf5d4bf5a52896ca1a589ea8b7
    ports:
      - "80:80"
      - "8080:8080" # traefik dashboard
    networks:
      - leaf_serverless_network
    depends_on:
      - redis-server
  whoami:
    image: traefik/whoami # example 
    depends_on:
      - reverse-proxy
    networks:
      - leaf_serverless_network
  leaf-runner:
    image: ghcr.io/fuxiaohei/leaf-runner:latest
    depends_on:
      - reverse-proxy
    ports:
      - '19980-19990:19988'
    deploy:
      replicas: 2
    networks:
      - leaf_serverless_network
