version: '3'

networks:
  leaf_serverless_network:
    external: true

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - leaf_serverless_network
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.X-Wasm=user.wasm"
      - "traefik.http.middlewares.testheader.headers.customrequestheaders.X-Custom-Request-Header=custom-header"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.middlewares=testHeader@docker"
    networks:
      - leaf_serverless_network
