[package]
name = "leaf-bin"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
tokio = { version = "1.25.0", features = ["full"] }
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_info"] }
tracing-subscriber = { version = "0.3.16", features = ["time", "local-time"] }
hyper = { version = "1.0.0-rc.2", features = ["full"] }
bytes = "1.4.0"
http-body-util = "0.1.0-rc.2"

[[bin]]
name = "leaf-cli"
path = "src/cli/main.rs"
doctest = false
test = false
