[package]
name = "leaf-bin"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]

[[bin]]
name = "leaf-cli"
path = "src/cli/main.rs"
doctest = false
test = false