[package]
name = "leaf-bin"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0.69"
bytes = "1.4.0"
clap = { version = "4.1.4", features = ["derive"] }
common = { path = "../common" }
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.2", features = ["full"] }
time = "0.3.17"
tokio = { version = "1.25.0", features = ["full"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16", features = [
    "time",
    "local-time",
    "env-filter"
] }

[[bin]]
name = "leaf-cli"
path = "src/cli/main.rs"
doctest = false
test = false
