[package]
name = "leaf-sdk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow =  { workspace =true }
bytes =  { workspace =true }
http =  { workspace =true }
wit-bindgen-guest-rust = { workspace =true }
