[package]
name = "common"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = "1.0.69"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.7.2"
