[package]
name = "leaf-host-kv"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
time = "0.3.17"

[dev-dependencies]
tokio = { workspace = true }
