name: Build

on:
  push:
    branches:
      - main

jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add clippy
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasi

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "leaf-builder"

      - name: Build
        run: |
          cargo run --bin leaf-cli --release help
          cargo run --bin leaf-cli --release -- --version

      - name: Test ABI impl
        run: |
          cargo test --release --workspace

      - name: Build Examples
        run: |
          (cd examples/rust-basic/ && ../../target/release/leaf-cli build)
          (cd examples/rust-fetch/ && ../../target/release/leaf-cli build)

      - name: Upload cli binary
        uses: actions/upload-artifact@v3
        with:
          name: leaf-cli
          path: target/release/leaf-cli

  build_rust_basic:
    runs-on: ubuntu-latest
    needs: build_all
    steps:
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasi
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-basic"

      - name: Download cli binary
        uses: actions/download-artifact@v3
        with:
          name: leaf-cli
      - name: Build project
        run: |
          chmod +x ./leaf-cli
          ./leaf-cli --version
          ./leaf-cli init hello-rust
          cd hello-rust
          ../leaf-cli build
          ../leaf-cli test

  build_js_basic:
    if: ${{ false }} # FIXME: disable until wasi issue fixed
    runs-on: ubuntu-latest
    needs: build_all
    steps:
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasi
          cargo install wizer --all-features

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "js-basic"

      - name: Download cli binary
        uses: actions/download-artifact@v3
        with:
          name: leaf-cli
      - name: Build project
        run: |
          chmod +x ./leaf-cli
          ./leaf-cli --version
          ./leaf-cli init hello-js --template=js-basic
          cd hello-js
          ../leaf-cli build
          ../leaf-cli test
