name: Build

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main

jobs:

  build_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - uses: Swatinem/rust-cache@v2
      
      - name: Build
        run: |
          cargo run --release help
          cargo run --release -- --version
