name: Build

on:
  push:
    branches:
      - main

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add clippy
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasi

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo run --release help
          cargo run --release -- --version

      - name: Test ABI impl
        run: |
          cargo test --release

      - name: Upload cli binary
        uses: actions/upload-artifact@v3
        with:
          name: leaf-cli
          path: target/release/leaf-cli

  build_project:
    runs-on: ubuntu-latest
    needs: build_latest
    steps:
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasi
      - name: Download cli binary
        uses: actions/download-artifact@v3
        with:
          name: leaf-cli
      - name: Build project
        run: |
          chmod +x ./leaf-cli
          ./leaf-cli --version
          ./leaf-cli new hello-rust
          cd hello-rust
          ../leaf-cli compile